#!/bin/bash

declare -a lines
processing=false

dbus-monitor "interface='org.freedesktop.Notifications'" | while read -r line; do
    if echo "$line" | grep -q "member=Notify"; then
        processing=true    
        lines=()
    fi

    if $processing; then
        case "$line" in
            *array*)
                processing=false
                caption=$(echo "${lines[4]}" | cut -d' ' -f2- | tr -d '"')
                message=$(echo "${lines[5]}" | cut -d' ' -f2- | tr -d '"') 

                waynot send "$caption" "$message"

                lines=()

                ;;
            *)
                lines+=("$line")
                ;;
        esac

    fi
done


